title: "KCSDA 중국조선족재림교회"
author: "Joshua"
description: "Copy right by KCSDA"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title Home Change, icon; home}
  - {file: "README.md", title About me, icon; address-card}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yhmedia@pronton.me"}
  - {title: Github, icon: github, url: "https://yhrhee.github.com/"}
  - {title: twitter, icon: github, url: "https://twitter.com/iyhrhee"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
